// Generated by CoffeeScript 1.6.2
var NodeResourceMonitor, Server, express;

express = require('express');

NodeResourceMonitor = require('./node_resource_monitor');

Server = (function() {
  function Server() {
    var app;

    app = express();
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express["static"](__dirname + '/../public'));
    app.set('views', __dirname + '/../views');
    app.set('view engine', 'ejs');
    this.app = app;
    this.monitor = new NodeResourceMonitor();
    this.setRoutes();
  }

  Server.prototype.setRoutes = function() {
    var app, self;

    app = this.app;
    self = this;
    app.get('/', function(req, res) {
      return res.render('index', {
        title: 'Node Resource Monitor'
      });
    });
    return app.get('/data', function(req, res) {
      return res.json(self.monitor.get());
    });
  };

  Server.prototype.start = function() {
    this.app.listen(5000);
    this.monitor.start(1000);
    return console.log("Server is listening to 5000");
  };

  Server.prototype.shutdown = function() {
    this.app.close();
    return this.monitor.stop();
  };

  return Server;

})();

module.exports = Server;
